services:
  app_dev:
    build:
      context: .
      # target: prod # Only keep this if you have "AS prod" in your Dockerfile
    image: jee-backend/backend:local
    container_name: development
    restart: always 
    env_file:
      - .env 
    ports: 
      - "3000:3005" 
      - "3005:3005"
