import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(__dirname, "../../.env") });


export const {
  PORT,
  JWT_SECRET_ACCESS_TOKEN,
  JWT_TEMP_EXPIRES_IN_ACCESS_TOKEN,
  JWT_ALGORITHM_ACCESS_TOKEN,
  JWT_SECRET_REFERSH_TOKEN,
  JWT_TEMP_EXPIRES_IN_REFERSH_TOKEN,
  JWT_ALGORITHM_REFERSH_TOKEN,
  DATABASE_URL,
  DATABASE_REPICA_URL,
  REDIS_HOST,
  REDIS_PORT,
  EMAIL_ID,
  GOOGLE_AUTH_PASSWORD,
  RABBITMQ_CONNECTION,
  RABBITMQ_PASSWORD,
  RABBITMQ_PORT,
  OTP_EXPIRE_TIME,
  SALT_ROUND,
  MAX_ATTEMENTS,
  WINDOW_SIZE,
  REDIS_PASSWORD,
  REDIS_USERNAME,
  BREVO_KEY_1,
  BREVO_KEY_2,
  GEMINI_API_KEY,
  BACKBLAZE_REGION,
  BACKBLAZE_ENDPOINT,
  BUCKET_NAME,
  IMAGE_EXPIRE_TIME,
  BACKBLAZE_KEY_ID,      // Ensure this exists in your config/env.ts
  BACKBLAZE_APP_KEY,
  IV_LENGTH,
  ENCRYPTION_KEY,
  BUCKET_ID,
  IMAGE_WORKER_BASE_URL,
  EMAIL_WORKER_PORT,
  UPDATE_WORKER_PORT,
  WATCHDOG_PORT,
  WATCHDOG_INTERVAL,
  WATCHDOG_INACTIVITY_THRESHOLD_SEC,
  EVALUATION_WORKER_PORT,
  STUDENT_TEST_ANALYTICS_WORKER_PORT
} = process.env;