import dotenv from "dotenv";
import path from "path";

process.env.DOTENV_QUIET = "true";
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

function requireEnv(key: string): string {
    const value = process.env[key];
    if (!value) {
        throw new Error(`Missing required environment variable: "${key}"`);
    }
    return value;
}

export const {
    NOMIC_API_KEY,
    PORT,
    SUBMIT_CHAPTER_WISE_PORT,
    JWT_SECRET_ACCESS_TOKEN,
    JWT_TEMP_EXPIRES_IN_ACCESS_TOKEN,
    JWT_ALGORITHM_ACCESS_TOKEN,
    JWT_SECRET_REFERSH_TOKEN,
    JWT_TEMP_EXPIRES_IN_REFERSH_TOKEN,
    JWT_ALGORITHM_REFERSH_TOKEN,
    DATABASE_URL,
    DATABASE_URL_PRODUCTION,
    DATABASE_REPICA_URL,
    REDIS_HOST,
    REDIS_PORT,
    EMAIL_ID_1,
    EMAIL_ID_2,
    EMAIL_ID_3,
    EMAIL_ID_4,
    EMAIL_ID_5,
    GOOGLE_AUTH_PASSWORD,
    RABBITMQ_CONNECTION,
    RABBITMQ_PASSWORD,
    RABBITMQ_PORT,
    OTP_EXPIRE_TIME,
    SALT_ROUND,
    MAX_ATTEMENTS,
    WINDOW_SIZE,
    REDIS_PASSWORD,
    REDIS_USERNAME,
    BREVO_KEY_1,
    BREVO_KEY_2,
    BREVO_KEY_3,
    BREVO_KEY_4,
    BREVO_KEY_5,
    GEMINI_API_KEY,
    BACKBLAZE_REGION,
    BACKBLAZE_ENDPOINT,
    BUCKET_NAME,
    IMAGE_EXPIRE_TIME,
    BACKBLAZE_KEY_ID,
    BACKBLAZE_APP_KEY,
    IV_LENGTH,
    ENCRYPTION_KEY,
    BUCKET_ID,
    IMAGE_WORKER_BASE_URL,
    EMAIL_WORKER_PORT,
    UPDATE_WORKER_PORT,
    WATCHDOG_PORT,
    WATCHDOG_INTERVAL,
    WATCHDOG_INACTIVITY_THRESHOLD_SEC,
    EVALUATION_WORKER_PORT,
    STUDENT_TEST_ANALYTICS_WORKER_PORT,
    EMAIL_ADDING_WORKER_PORT,
    TOKEN_BUCKET_CAPACITY,
    TOKEN_BUCKET_REFLIER,
    QUESTION_STORE_REDIS_URL,
    QUESTION_STORE_REDIS_PORT,
    QUESTION_STORE_REDIS_USERNAME,
    QUESTION_STORE_REDIS_HOST,
    QUESTION_STORE_REDIS_PASSWORD,
    GOOGLE_CLIENT_ID,
    REDIS_CACHE_EXPIRATION_SECONDS
} = process.env;
