import dotenv from "dotenv" ;
dotenv.config() ; 

export const {
    PORT,
    JWT_SECRET_ACCESS_TOKEN , 
    JWT_TEMP_EXPIRES_IN_ACCESS_TOKEN,
    JWT_ALGORITHM_ACCESS_TOKEN,
    JWT_SECRET_REFERSH_TOKEN , 
    JWT_TEMP_EXPIRES_IN_REFERSH_TOKEN,
    JWT_ALGORITHM_REFERSH_TOKEN,
    DATABASE_URL ,
    DATABASE_REPICA_URL,
    REDIS_HOST,
    REDIS_PORT,
    EMAIL_ID,
    GOOGLE_AUTH_PASSWORD,
    RABBITMQ_CONNECTION,
    OTP_EXPIRE_TIME,
    SALT_ROUND,
    MAX_ATTEMENTS, 
    WINDOW_SIZE

} = process.env ; 

